#!/usr/bin/env python3
"""
TokenBroker – Weekly arXiv Trend Observer
==========================================
Fetches recent papers on multi-agent systems from arXiv, summarises them
via the TokenBroker proxy, and appends a report to docs/.

Usage:
    python infra/arxiv_trends.py [--max-results 10] [--dry-run]

Schedule (cron, weekly on Monday 07:00):
    0 7 * * 1 cd /path/to/TokenBroker && python infra/arxiv_trends.py
"""
from __future__ import annotations

import argparse
import os
import time
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(Path(__file__).parent.parent / "backend" / ".env")

PROXY_URL = "https://yondem-production.up.railway.app/v1/chat/completions"
API_KEY   = os.getenv("TOKENBROKER_KEY", "tkb_test_123")
DOCS_DIR  = Path(__file__).parent.parent / "docs"

ARXIV_BASE = "https://export.arxiv.org/api/query"
ARXIV_NS   = "http://www.w3.org/2005/Atom"

QUERIES = [
    "multi-agent systems LLM",
    "autonomous agent swarm optimization",
    "reinforcement learning multi-agent code generation",
]


# ── arXiv fetch ────────────────────────────────────────────────────────────────

def fetch_papers(query: str, max_results: int = 5) -> list[dict]:
    params = urllib.parse.urlencode({
        "search_query": f"all:{query}",
        "start": 0,
        "max_results": max_results,
        "sortBy": "submittedDate",
        "sortOrder": "descending",
    })
    url = f"{ARXIV_BASE}?{params}"
    try:
        with urllib.request.urlopen(url, timeout=15) as resp:
            xml_data = resp.read()
    except urllib.error.URLError as exc:
        print(f"  [arXiv] fetch failed for '{query}': {exc}")
        return []

    root = ET.fromstring(xml_data)
    papers = []
    for entry in root.findall(f"{{{ARXIV_NS}}}entry"):
        title = entry.findtext(f"{{{ARXIV_NS}}}title", "").strip().replace("\n", " ")
        summary = entry.findtext(f"{{{ARXIV_NS}}}summary", "").strip().replace("\n", " ")[:400]
        published = entry.findtext(f"{{{ARXIV_NS}}}published", "")[:10]
        link = ""
        for l in entry.findall(f"{{{ARXIV_NS}}}link"):
            if l.get("type") == "text/html":
                link = l.get("href", "")
        papers.append({
            "title": title,
            "summary": summary,
            "published": published,
            "url": link,
            "query": query,
        })
    return papers


# ── LLM summarisation ─────────────────────────────────────────────────────────

def summarise_papers(papers: list[dict]) -> str:
    """Ask the proxy to extract architecture recommendations from papers."""
    if not papers:
        return "No papers found."

    bullets = "\n".join(
        f"- [{p['published']}] {p['title']}: {p['summary']}" for p in papers
    )
    prompt = (
        "You are a research analyst for an AI infrastructure startup. "
        "Given the following recent arXiv papers on multi-agent systems, "
        "write 3–5 concrete architecture recommendations for our self-optimising "
        "agent swarm that converts legacy code. Be specific and actionable. "
        "Output plain text, no markdown.\n\n"
        f"Papers:\n{bullets}"
    )

    import json
    import urllib.request as req

    payload = json.dumps({
        "messages": [
            {"role": "system", "content": "You are a senior AI systems architect."},
            {"role": "user", "content": prompt},
        ]
    }).encode()

    request = urllib.request.Request(
        PROXY_URL,
        data=payload,
        headers={
            "Authorization": f"Bearer {API_KEY}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=60) as resp:
            data = json.loads(resp.read())
        return data["choices"][0]["message"]["content"].strip()
    except Exception as exc:
        return f"(LLM summarisation failed: {exc})"


# ── Report writer ──────────────────────────────────────────────────────────────

def write_report(papers: list[dict], recommendations: str, dry_run: bool) -> Path:
    date_str = time.strftime("%Y-%m-%d")
    report_path = DOCS_DIR / f"arxiv_trends_{date_str}.md"

    lines = [
        f"# arXiv Trends – {date_str}",
        "",
        f"Automatically generated by `infra/arxiv_trends.py`. "
        f"{len(papers)} papers analysed.",
        "",
        "## Architecture Recommendations",
        "",
        recommendations,
        "",
        "## Papers",
        "",
    ]
    for p in papers:
        lines += [
            f"### {p['title']}",
            f"- **Published**: {p['published']}",
            f"- **Query**: {p['query']}",
            f"- **URL**: {p['url']}",
            f"- **Abstract**: {p['summary']}",
            "",
        ]

    content = "\n".join(lines)
    if dry_run:
        print("\n── DRY RUN – report not saved ──")
        print(content[:1000], "...\n")
    else:
        DOCS_DIR.mkdir(exist_ok=True)
        report_path.write_text(content, encoding="utf-8")
        print(f"Report saved: {report_path}")
    return report_path


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Weekly arXiv trend observer")
    parser.add_argument("--max-results", type=int, default=5,
                        help="Papers per query (default 5)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print report without saving")
    args = parser.parse_args()

    print(f"Fetching arXiv papers ({len(QUERIES)} queries × {args.max_results} results)...")
    all_papers: list[dict] = []
    for q in QUERIES:
        print(f"  query: {q}")
        papers = fetch_papers(q, args.max_results)
        print(f"    → {len(papers)} papers")
        all_papers.extend(papers)

    # Deduplicate by URL
    seen: set[str] = set()
    unique: list[dict] = []
    for p in all_papers:
        if p["url"] not in seen:
            seen.add(p["url"])
            unique.append(p)
    print(f"\n{len(unique)} unique papers found.")

    print("Summarising via TokenBroker proxy...")
    recommendations = summarise_papers(unique)

    write_report(unique, recommendations, args.dry_run)


if __name__ == "__main__":
    main()
