"""
Planner – Reads NEXT_SESSION.md and generates tasks/todo.md.

Output format (tasks/todo.md):
  ## Priority 1 – Critical
  - [ ] Task A  [dep: none]
  - [ ] Task B  [dep: Task A]

  ## Priority 2 – Important
  - [ ] Task C  [dep: none]

  ## Priority 3 – Nice-to-have
  - [ ] Task D
"""
from __future__ import annotations

import re
import time
from pathlib import Path
from typing import Any


_PRIORITIES = {
    "critical":  1,
    "bug":       1,
    "fix":       1,
    "security":  1,
    "important": 2,
    "feature":   2,
    "improve":   2,
    "refactor":  2,
    "test":      2,
    "doc":       3,
    "nice":      3,
    "optional":  3,
    "cleanup":   3,
}

_HEADING_RE = re.compile(r"^#{1,3}\s+(.+)", re.M)
_BULLET_RE  = re.compile(r"^[-*]\s+(.+)", re.M)
_TASK_RE    = re.compile(
    r"^[-*]\s+(?:\[[ x]\]\s+)?(.+)", re.M | re.I
)


class Task:
    def __init__(self, title: str, priority: int = 2, deps: list[str] | None = None) -> None:
        self.title = title.strip()
        self.priority = priority
        self.deps: list[str] = deps or []
        self.done = False

    def _infer_priority(self) -> None:
        low = self.title.lower()
        for keyword, p in _PRIORITIES.items():
            if keyword in low:
                self.priority = p
                return

    def to_md(self) -> str:
        dep_str = f"  [dep: {', '.join(self.deps)}]" if self.deps else ""
        check = "[x]" if self.done else "[ ]"
        return f"- {check} {self.title}{dep_str}"


class Planner:
    """
    Parses NEXT_SESSION.md and writes a prioritised, dependency-aware
    task list to tasks/todo.md.

    Usage::

        planner = Planner(repo_root=Path("."))
        plan = planner.generate_plan()
        print(plan["total_tasks"])
    """

    def __init__(self, repo_root: Path) -> None:
        self.root = repo_root
        self.next_session_path = repo_root / "NEXT_SESSION.md"
        self.todo_path = repo_root / "tasks" / "todo.md"

    def generate_plan(self) -> dict[str, Any]:
        """Read NEXT_SESSION.md and write tasks/todo.md. Returns summary dict."""
        source = ""
        if self.next_session_path.exists():
            source = self.next_session_path.read_text(encoding="utf-8", errors="replace")

        tasks = self._extract_tasks(source)
        self._assign_dependencies(tasks)
        self._write_todo(tasks)

        by_priority: dict[int, int] = {}
        for t in tasks:
            by_priority[t.priority] = by_priority.get(t.priority, 0) + 1

        return {
            "total_tasks": len(tasks),
            "by_priority": by_priority,
            "output_path": str(self.todo_path),
            "source_path": str(self.next_session_path),
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        }

    # ── Internal ──────────────────────────────────────────────────────────────

    def _extract_tasks(self, source: str) -> list[Task]:
        tasks: list[Task] = []
        seen: set[str] = set()

        for m in _TASK_RE.finditer(source):
            title = m.group(1).strip()
            if not title or title in seen or len(title) < 5:
                continue
            # Skip markdown table separators and purely decorative lines
            if re.match(r"^[-|:]+$", title):
                continue
            seen.add(title)
            t = Task(title)
            t._infer_priority()
            tasks.append(t)

        # If NEXT_SESSION.md had no bullet items, fall back to section headings
        if not tasks:
            for m in _HEADING_RE.finditer(source):
                title = m.group(1).strip()
                if len(title) > 5:
                    t = Task(title)
                    t._infer_priority()
                    tasks.append(t)

        return tasks

    def _assign_dependencies(self, tasks: list[Task]) -> None:
        """
        Simple heuristic: a task that mentions another task's title
        (or a keyword from it) depends on that earlier task.
        """
        for i, t in enumerate(tasks):
            for j, prev in enumerate(tasks[:i]):
                # Short word overlap check (>= 2 significant words in common)
                t_words = set(re.findall(r"\b\w{5,}\b", t.title.lower()))
                p_words = set(re.findall(r"\b\w{5,}\b", prev.title.lower()))
                if len(t_words & p_words) >= 2:
                    t.deps.append(prev.title[:40])

    def _write_todo(self, tasks: list[Task]) -> None:
        self.todo_path.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            "# TokenBroker – Task Backlog",
            f"_Generated by CTO Agent – {time.strftime('%Y-%m-%d %H:%M UTC')}_",
            "",
        ]
        for priority, label in [(1, "Critical"), (2, "Important"), (3, "Nice-to-have")]:
            group = [t for t in tasks if t.priority == priority]
            if not group:
                continue
            lines += [f"## Priority {priority} – {label}", ""]
            for t in group:
                lines.append(t.to_md())
            lines.append("")

        self.todo_path.write_text("\n".join(lines))
